# Generated by Django 4.1.6 on 2023-02-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="pizza", name="size",),
        migrations.RemoveField(model_name="pizza", name="toppings",),
        migrations.RemoveField(model_name="pizza", name="user",),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizza_app.pizza",
                    ),
                ),
            ],
        ),
    ]
